# Generated by Django 5.1.6 on 2025-02-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlog',
            options={'ordering': ['-log_date']},
        ),
    ]
