# Generated by Django 5.1 on 2025-03-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlog', '0002_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='migraines_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlog.user_login')),
            ],
            options={
                'ordering': ['log_date'],
            },
        ),
    ]
