# Generated by Django 5.1.6 on 2025-02-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlog', '0002_alter_dlog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlog',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='dlog',
            name='log_date',
            field=models.DateField(unique=True),
        ),
    ]
