# Generated by Django 5.1 on 2025-03-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlog', '0003_migraines_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='simple_log',
        ),
    ]
