# Generated by Django 5.1.6 on 2025-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlog', '0005_alter_dlog_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlog',
            name='log_date',
            field=models.DateField(),
        ),
    ]
