# Generated by Django 5.1.6 on 2025-03-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlog', '0007_alter_dlog_log_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlog',
            options={'ordering': ['log_date']},
        ),
        migrations.AlterField(
            model_name='dlog',
            name='log_date',
            field=models.DateField(),
        ),
    ]
